CREATE DATABASE projetojava;
USE projetojava;

CREATE TABLE usuario(
id BIGINT(10) PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR (255),
cpf VARCHAR (255),
email VARCHAR(255),
telefone VARCHAR (255)
);

SELECT*FROM usuario;